// <auto-generated />
namespace eCommerce.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_list_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_list_users));
        
        string IMigrationMetadata.Id
        {
            get { return "201610161658418_test_list_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
